"""empty message

Revision ID: 1d31177f380e
Revises: aabeca5612c1
Create Date: 2022-07-17 23:00:28.308045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d31177f380e'
down_revision = 'aabeca5612c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'movies', ['title'])
    op.create_unique_constraint(None, 'streamingplatforms', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'streamingplatforms', type_='unique')
    op.drop_constraint(None, 'movies', type_='unique')
    # ### end Alembic commands ###
