"""empty message

Revision ID: 8acbe458de5f
Revises: 
Create Date: 2022-07-21 16:06:49.003727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8acbe458de5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movies_title_key', 'movies', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('movies_title_key', 'movies', ['title'])
    # ### end Alembic commands ###
