"""empty message

Revision ID: 9ffb76723b1c
Revises: 
Create Date: 2022-07-10 18:14:15.316029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffb76723b1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streamingplatforms', sa.Column('num_movies', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streamingplatforms', 'num_movies')
    # ### end Alembic commands ###
